name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build with Docker using devkitARM
    steps:
      - name: Install Python
        run: sudo apt-get -y install python
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Build dsidl
        run: |
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dsidl.dsi
          path: dsidl.dsi