name: Release

on:
    release:
        types:
            - published
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build with Docker using devkitARM
    steps:
      - name: Install Python
        run: sudo apt-get -y install python
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Build dsidl
        run: |
          make
      
      - name: Upload GitHub release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: dsidl.dsi
          repo-token: ${{ secrets.GITHUB_TOKEN }}